version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    versioning-strategy: increase
