name: Verify
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-verify:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check Node Version
        run: node --version

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          npm install
          npm run lint
          npm run build

      - name: Google Chat Notification (Always)
        if: github.event_name == 'push' && always()
        uses: Co-qn/google-chat-notification@b9227d9daa4638c9782a5bd16c4abb86268127a1
        with:
          name: ${{ github.job }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}

      - name: Google Chat Notification (Error)
        if: github.event_name == 'push' && failure()
        uses: Co-qn/google-chat-notification@b9227d9daa4638c9782a5bd16c4abb86268127a1
        with:
          name: ${{ github.job }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_ERRORS }}
          status: ${{ job.status }}